import {Game,loadSave,W,H} from './engine.js';
import {CLASSES,ENEMIES,ITEMS,TALENTS,UPGRADES,CAUSES,itemBy,enemyBy} from './data.js';
const app=document.querySelector('#app'),overlay=document.querySelector('#overlay');
let storage;try{storage=localStorage;}catch{storage={getItem:()=>null,setItem:()=>{throw Error('unavailable')}};}
const game=new Game(loadSave(storage));let selected='warden',view=game.r?.status==='alive'?'play':'home',panel=null,tab='BODY',targetIndex=null,inspect=false,saveError=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){try{storage.setItem('remains-v1',JSON.stringify(game.s));saveError=false;}catch{saveError=true;toast('保存できません。ブラウザの空き容量・設定を確認してください。');}}
function toast(s){const e=document.querySelector('#toast');e.textContent=s;e.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.style.display='none',3000);}
const btn=(label,action,cls='',extra='')=>`<button class="${cls}" data-action="${action}" ${extra}>${label}</button>`;
function mast(play=false){return `<header class="mast"><span class="logo">REMAINS<span style="color:var(--moss)">.</span></span>${play?btn('休息地へ','home','back'):'<span class="version">A WORLD THAT REMEMBERS · v0.1</span>'}</header>`;}
function render(){app.innerHTML=view==='play'&&game.r?play():home();renderPanel();}
function home(){const deaths=game.s.graves.length,world=UPGRADES.filter(u=>u.group==='WORLD'&&game.up(u.id)).length;return `<main class="wrap">${mast()}<section class="home"><div class="hero"><div class="eyebrow">DEATH IS ONLY THE BEGINNING</div><div class="seal" aria-hidden="true">♜</div><h1>REMAINS</h1><h2>死は、世界に残る。</h2><p>あなたは失われる。けれど、すべてではない。<br>骨に、記憶に、まだ見ぬ世界に。<br>次の誰かのために、もう一度、地下へ。</p><div class="hero-foot"><span>◇ ${deaths} の墓碑</span><span>✧ ${world} の世界変化</span><span>↓ 全10層</span></div></div><div class="departure"><div class="section-label"><h2>次に灯りを持つ者</h2><span class="soul">✧ ${game.s.souls} 残響</span></div><div class="class-list">${CLASSES.filter(c=>!c.unlock||game.s.unlocks.includes(c.unlock)).map(c=>`<button class="class-card ${selected===c.id?'selected':''}" data-action="class:${c.id}" aria-pressed="${selected===c.id}"><span class="class-icon">${c.icon}</span><span><b>${c.name}</b><small>${c.desc}</small></span><span>${selected===c.id?'●':'○'}</span></button>`).join('')}</div>${game.r?.status==='alive'?btn('<span>灯りは、まだ消えていない</span><span>冒険を再開 →</span>','resume','primary start'):btn('<span>地下へ、灯りをひとつ</span><span>冒険を始める ↓</span>','start','primary start')}<div class="subline">ターン制 · 自動セーブ · 1回 約5〜20分</div>${saveError?'<p class="save-warning">保存できない状態です</p>':''}</div></section><nav class="home-nav">${btn('<span>Ⅰ　残響を刻む</span><small>身体・知識・世界を育てる</small>','upgrades')}${btn('<span>Ⅱ　墓碑の庭</span><small>'+deaths+'人の、終わりの記録</small>','graves')}${btn('<span>Ⅲ　観察手帳</span><small>知らないものを、知る</small>','codex')}</nav><footer class="foot"><span>死ぬたびに、世界は少し違う。</span>${btn('遊び方','help','back')}</footer></main>`;}
function tile(x,y){const r=game.r,p=game.p,seen=r.seen[y][x],vis=r.visible.includes(y*W+x);let cls=seen?(r.map[y][x]==='#'?'wall':'floor'):'unknown',glyph=seen&&r.map[y][x]==='.'?'·':'',label=seen?(r.map[y][x]==='#'?'壁':'床'):'未探索',hp='';if(seen){if(x===r.stairs.x&&y===r.stairs.y){cls='stairs';glyph='≋';label='階段';}const s=r.sites.find(s=>s.x===x&&s.y===y);if(s){cls='site';glyph=s.type==='grave'?'†':s.type==='smith'?'⚒':'♧';label=s.type==='grave'?'過去の冒険者の墓':s.type==='smith'?'鍛冶屋':'祭壇';if(s.used)cls+=' fog';}const t=r.traps.find(t=>t.x===x&&t.y===y);if(t&&(t.used||game.up('taste'))){cls='trap';glyph=t.used?'·':'△';label=t.type==='fire'?'炎の罠':'毒の罠';}const l=r.loot.find(i=>i.x===x&&i.y===y);if(l){cls='loot';glyph=['weapon','armor'].includes(itemBy(l.id).type)?'⌁':'♢';label=itemBy(l.id).name;}if(!vis)cls+=' fog';}
 const e=vis&&r.enemies.find(e=>e.x===x&&e.y===y);if(e){const b=enemyBy(e.id);cls='enemy '+(b.id==='boss'?'boss':'');glyph=b.glyph;label=b.name;if(game.up('sight')||p.eye){hp=`<span class="ehp"><i style="width:${Math.max(0,e.hp/e.maxHp*100)}%"></i></span>`;label+=' HP '+e.hp;}}if(p.x===x&&p.y===y){cls='player';glyph='@';label='あなた';}return `<button class="tile ${cls}" data-x="${x}" data-y="${y}" aria-label="${esc(label)}" tabindex="-1">${glyph}${hp}</button>`;}
function play(){const r=game.r,p=game.p,c=CLASSES.find(c=>c.id===r.class);return `<main class="wrap play-wrap">${mast(true)}<div class="game-layout"><section class="dungeon"><div class="game-top"><div><div class="eyebrow">${game.up('garden')&&r.floor>3?'THE SPORE GARDEN':'BENEATH THE ROOTS'}</div><h2>${game.up('garden')&&r.floor>3?'胞子の庭':'根の下の迷宮'}</h2></div><span class="floor-label">${String(r.floor).padStart(2,'0')} <small style="font:11px sans-serif">/ 10</small></span></div><div class="vitals"><div class="hp-label"><span>${c.icon} ${esc(r.name)} <span class="muted">Lv.${p.level}</span></span><span>HP ${p.hp} / ${p.maxHp}</span></div><div class="bar hp ${p.hp<p.maxHp*.35?'low':''}"><i style="width:${p.hp/p.maxHp*100}%"></i></div><div class="food">♧ ${p.food}<small> / 100</small></div><div class="bar xp"><i style="width:${Math.min(100,p.xp/(p.level*10)*100)}%"></i></div></div>${targetIndex!==null?`<div class="target-banner">投げる敵をタップ（5マス以内）${btn('取消','cancel-target')}</div>`:inspect?`<div class="target-banner">調べるマスをタップ${btn('取消','cancel-target')}</div>`:''}<div class="board" aria-label="ダンジョン。方向キーまたはスワイプで移動">${Array.from({length:H},(_,y)=>Array.from({length:W},(_,x)=>tile(x,y)).join('')).join('')}</div><div class="board-caption"><span>@ あなた　 · 敵にぶつかると攻撃</span><span>≋ 階段　♢ 道具　† 墓</span></div><div class="status-line">${p.poison?'毒 '+p.poison+'　':''}${p.fire?'炎 '+p.fire+'　':''}${p.food<20?'お腹が鳴っている。　':''}${atSite()}</div></section><aside class="side"><div class="side-title">FIELD NOTES / 冒険の記録</div><div class="log" aria-live="polite">${r.log.slice(0,5).map(l=>'<p>'+esc(l)+'</p>').join('')}</div><div class="controls"><div class="actions">${btn(c.skill+(p.cool?' · '+p.cool:' ✧'),'skill','skill',p.cool?'disabled':'')}${btn('鞄 '+p.bag.length+'/'+(9+game.up('pocket')*3),'bag')}${btn('調べる / 降りる','interact')}${btn('観察する','inspect')}${btn('身体 / 能力','build')}</div><div class="dpad" aria-label="移動">${btn('↑','move:0:-1','up','aria-label="上へ移動"')}${btn('←','move:-1:0','left','aria-label="左へ移動"')}${btn('·','wait','','aria-label="1ターン待つ"')}${btn('→','move:1:0','','aria-label="右へ移動"')}${btn('↓','move:0:1','down','aria-label="下へ移動"')}</div></div><div class="build"><div class="muted">${esc(itemBy(p.weapon)?.name||'素手')} / ${esc(itemBy(p.armor)?.name||'旅の服')}</div><div class="tags">${p.talents.length?p.talents.map(id=>'<span class="tag">'+TALENTS.find(t=>t.id===id).name+'</span>').join(''):'<span class="muted">まだ、何者でもない。</span>'}</div></div><p class="game-help">あなたが動くまで、世界も動かない。<br>回復薬も、撤退の一歩も、同じ1ターン。<br>死のあとに残るのは、強さだけではない。</p><div class="legend"><span>WASD / 矢印 移動</span><span>Space 待機</span><span>E 調べる</span></div></aside></div></main>`;}
function atSite(){const r=game.r,p=game.p,s=r.sites.find(s=>s.x===p.x&&s.y===p.y&&!s.used);if(s)return s.type==='smith'?'⚒ 鍛冶屋：HP−5で鍛造+2。調べるで取引。':s.type==='altar'?'♧ 祭壇：HP−6で攻撃+2。調べるで祈る。':'† 墓碑がある。調べてみよう。';if(p.x===r.stairs.x&&p.y===r.stairs.y)return r.floor===10?'≋ 王を討ち、調べるで生を世界へ還す。':'≋ 「調べる / 降りる」で次の階へ。';return '';}
function modal(title,body,closable=true){return `<div class="shade"><section class="modal" role="dialog" aria-modal="true" aria-label="${title}"><header class="modal-header"><h2>${title}</h2>${closable?btn('×','close','close','aria-label="閉じる"'):''}</header>${body}</section></div>`;}
function renderPanel(){let html='';const r=game.r;
 if(view==='play'&&r?.status!=='alive'){const g=r.result;html=modal('灯りは、消えた。',`<div class="death"><div class="eyebrow">${r.status==='victory'?'THE ROOTS REMEMBER':'NOTHING IS ENTIRELY LOST'}</div><div class="death-mark">${r.status==='victory'?'♛':'†'}</div><h2>${esc(g.name)}</h2><p>${esc(g.detail)}。</p><div class="death-summary"><small>到達階<span>${g.floor} F</span></small><small>レベル<span>${g.level}</span></small><small>倒した敵<span>${r.kills}</span></small></div><p>世界に残ったもの</p><div class="reward">+ ${g.reward} <small style="font-size:14px">残響</small></div>${r.newUnlocks.map(id=>`<p style="color:var(--moss)">新たな理解：${CAUSES[id]}。${id==='poison'?'菌の巡礼者と毒の能力が解禁。':id==='divine'?'神への領収書が能力候補に加わった。':'関連する能力が次の冒険に出現。'}</p>`).join('')}<p>墓碑が次の迷宮に現れる。<br>残響を刻んで、次の灯りを選ぼう。</p>${btn('残響を刻む →','after-death','primary')}</div>`,false);}
 else if(view==='play'&&r?.choices.length){html=modal('この生に、何を刻む？',`<p class="intro">LEVEL ${game.p.level} / この冒険だけの変化</p>${r.choices.map(id=>{const t=TALENTS.find(t=>t.id===id);return btn('<b>'+t.name+'</b><span>'+t.desc+'</span>','choose:'+id,'talent-choice');}).join('')}`,false);}
 else if(panel==='upgrades'){html=modal('残響を刻む',`<p class="intro">✧ ${game.s.souls} 残響 — 次の生と、次の世界へ。${r?.status==='alive'?'<br><span class="danger">冒険中は購入できません。残響は生を終えたあとに刻めます。</span>':''}</p><div class="tabs">${['BODY','KNOWLEDGE','WORLD'].map(t=>btn(t,'tab:'+t,t===tab?'active':'')).join('')}</div>${UPGRADES.filter(u=>u.group===tab).map(u=>{const level=game.up(u.id),cost=u.cost*(level+1),done=level>=u.max;return `<div class="upgrade"><div><h3>${u.name} <span class="rank">${level}/${u.max}</span></h3><p>${u.desc}</p></div>${btn(done?'刻印済':'✧ '+cost,'buy:'+u.id,'',done||game.s.souls<cost||r?.status==='alive'?'disabled':'')}</div>`;}).join('')}`);}
 else if(panel==='bag'){html=modal('旅の鞄',`<p class="intro">使う・装備・投げる・置く・壊す。行動すると1ターン経過。</p><div class="item-list">${game.p.bag.map((id,n)=>{const i=itemBy(id);return btn(esc(i.name)+'<small>'+(game.p.weapon===id||game.p.armor===id?'装備中':typeName(i.type))+(game.up('taste')&&['toxic','hot'].includes(i.tag)?' · ⚠ 危険':'')+'</small>','item:'+n);}).join('')||'<p>鞄は空っぽ。</p>'}</div>`);}
 else if(panel?.startsWith('item:')){const n=Number(panel.split(':')[1]),i=itemBy(game.p.bag[n]);if(i){const equip=['weapon','armor'].includes(i.type),usable=['food','potion','cure','poison','fire','map','heart','relic','eye','seed','scroll'].includes(i.type);html=modal(i.name,`<div class="eyebrow">${typeName(i.type)}</div><div class="item-detail"><p>${esc(i.lore)}</p>${equip?'<p>効果：'+(i.type==='weapon'?'攻撃':'防御')+' +'+i.power+'</p>':''}${game.up('taste')&&['toxic','hot'].includes(i.tag)?'<p class="danger">⚠ 食べると'+(i.tag==='toxic'?'毒':'炎')+'状態になります。</p>':''}</div><div class="item-actions">${equip?btn('装備','use:'+n+':equip','primary'):usable?btn(i.type==='food'?'食べる':'使う','use:'+n+':use','primary'):''}${btn('投げる','throw:'+n)}${btn('置く','use:'+n+':drop')}${btn('壊す','use:'+n+':break')}</div>`);}}
 else if(panel==='graves'){html=modal('墓碑の庭',`<p class="intro">${game.s.graves.length} 人が道を少しだけ延ばした。</p>${game.s.graves.map(g=>`<article class="grave"><h3>† ${esc(g.name)}</h3><small>${CLASSES.find(c=>c.id===g.class)?.name} · 第${g.floor}層 · Lv.${g.level} · ${g.turn}ターン</small><p class="cause">${esc(g.detail)}</p><p>${g.equipment.map(id=>itemBy(id)?.name).join(' / ')||'何も持たずに'}</p><small>${g.talents.map(id=>TALENTS.find(t=>t.id===id)?.name).join(' · ')}　✧ +${g.reward}</small></article>`).join('')||'<p>まだ墓碑はない。<br>それは、悪いことではない。</p>'}`);}
 else if(panel==='codex'){const ct=['enemies','items','causes','events'].includes(tab)?tab:'enemies';const labels={enemies:'生物',items:'道具',causes:'死因',events:'出来事'};const eventNames={poisontrap:'くしゃみをする床',firetrap:'灯りの罠',grave:'過去の冒険者',smith:'血払いの鍛冶屋',altar:'留守だった神',king:'根の下の王の終わり'};const entries=ct==='enemies'?ENEMIES:ct==='items'?ITEMS:ct==='causes'?Object.entries(CAUSES).map(([id,name])=>({id,name})):Object.entries(eventNames).map(([id,name])=>({id,name}));html=modal('観察手帳',`<p class="intro">経験したことだけが、ここに残る。 ${game.s.codex[ct].length} / ${entries.length}</p><div class="tabs">${Object.keys(labels).map(t=>btn(labels[t],'tab:'+t,ct===t?'active':'')).join('')}</div>${entries.map(i=>game.s.codex[ct].includes(i.id)?`<article class="codex-entry"><h3>${esc(i.name)}</h3><p>${esc(i.lore||'あなたの世界に、確かに存在した。')}</p>${ct==='enemies'&&game.up('anatomy')?'<small>基礎HP '+i.hp+' / 攻撃 '+i.atk+' / '+traitName(i.trait)+'</small>':''}</article>`:'<div class="unknown-entry">?　未記録</div>').join('')}`);}
 else if(panel==='build'){html=modal('この生のかたち',`<p>${CLASSES.find(c=>c.id===r.class).detail}</p><p>攻撃 ${game.p.atk+(itemBy(game.p.weapon)?.power||0)+game.p.forge} / 防御 ${itemBy(game.p.armor)?.power||0} / 経験 ${game.p.xp}/${game.p.level*10}</p><p>武器：${itemBy(game.p.weapon)?.name||'素手'}（鍛造 +${game.p.forge}）<br>防具：${itemBy(game.p.armor)?.name||'旅の服'}</p>${game.p.talents.map(id=>{const t=TALENTS.find(t=>t.id===id);return `<div class="codex-entry"><h3>${t.name}</h3><p>${t.desc}</p></div>`;}).join('')||'<p class="intro">敵を倒して、最初の能力を選ぼう。</p>'}`);}
 else if(panel==='help'){html=modal('灯りの持ち方',`<p class="intro">この迷宮はターン制。考えている間、敵は待ってくれます。</p><div class="codex-entry"><h3>歩く、戦う、拾う</h3><p>隣のマスをタップ、盤面をスワイプ、または下の方向ボタンで移動。離れた床をタップすると、その方向へ1歩。敵への移動で攻撃し、道具は足元で自動取得します。</p></div><div class="codex-entry"><h3>生き延びる</h3><p>鞄から回復・食事・装備・投擲。投げるときは視界内5マス以内の敵を選択。炎と毒は毎ターンHPを削ります。緑の紐には気をつけて。職業技も忘れずに。</p></div><div class="codex-entry"><h3>地下へ、さらに</h3><p>≋ の上で「調べる / 降りる」。階段は少し回復します。全10層、最深部には王。レベルアップでは今回だけの能力を選びます。</p></div><div class="codex-entry"><h3>死のあと</h3><p>残響をBODY・KNOWLEDGE・WORLDへ。WORLDは敵や施設を増やします。毒で2回、炎・飢餓・自爆で1回死ぬと新しい能力が出現。過去の墓は次の探索に現れます。</p></div><div class="codex-entry"><h3>キーボード / 保存</h3><p>矢印・WASD：移動 / Space：待機 / E：調べる / Q：職業技 / I：鞄 / Esc：閉じる。行動のたびにこのブラウザへ自動保存。ページを閉じても冒険を再開できます。</p></div>`);}
 else if(panel?.startsWith('observe:')){html=modal('観察',`<p>${esc(panel.slice(8))}</p>`);}
 const hadDialog=Boolean(overlay.innerHTML);overlay.innerHTML=html;if(html){overlay.querySelector('button')?.focus({preventScroll:true});}else if(hadDialog){app.querySelector('[data-action="bag"], [data-action="start"], [data-action="resume"]')?.focus({preventScroll:true});}
}
function typeName(t){return ({weapon:'武器',armor:'防具',food:'食料',potion:'回復',bomb:'爆発物',fire:'炎',poison:'毒',cure:'治療',scroll:'巻物',map:'地図',relic:'遺物',frost:'冷気'})[t]||'奇妙な道具';}
function traitName(t){return ({plain:'近接',armor:'硬い殻',fire:'炎',poison:'毒',fast:'近接',hunger:'食料を奪う',drain:'吸血',dragon:'炎の竜',divine:'神罰',boss:'王'})[t];}
function after(){save();render();}
function action(a){const [k,id,more]=a.split(':');if(k==='close'){panel=null;renderPanel();return;}if(k==='class'){selected=id;render();return;}if(k==='tab'){tab=id;renderPanel();return;}if(k==='home'){view='home';targetIndex=null;inspect=false;panel=null;render();return;}if(k==='resume'){view='play';render();return;}if(k==='start'){if(game.r?.status==='alive')return;game.start(selected);view='play';panel=null;after();return;}if(k==='after-death'){view='home';panel='upgrades';tab='BODY';after();return;}if(['upgrades','bag','graves','codex','help','build'].includes(k)){panel=k;if(k==='upgrades')tab='BODY';if(k==='codex')tab='enemies';renderPanel();return;}if(k==='buy'){if(game.buy(id))toast('世界に、新しい刻印が残った。');after();return;}if(k==='choose'){game.choose(id);after();return;}if(k==='item'){panel=a;renderPanel();return;}if(k==='throw'){targetIndex=Number(id);panel=null;render();return;}if(k==='cancel-target'){targetIndex=null;inspect=false;render();return;}
 if(view!=='play'||!game.ready())return;if(k==='use'){game.use(Number(id),more);panel=null;}if(k==='move')game.move(Number(id),Number(more));if(k==='wait')game.wait();if(k==='skill')game.skill();if(k==='interact')game.interact();if(k==='inspect'){inspect=true;render();return;}after();}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.action){action(b.dataset.action);return;}if(b.dataset.x!==undefined&&!overlay.innerHTML){if(Date.now()<suppressClick)return;const x=+b.dataset.x,y=+b.dataset.y;if(inspect){const r=game.r,enemy=r.enemies.find(e=>e.x===x&&e.y===y&&game.visible(e)),loot=r.loot.find(i=>i.x===x&&i.y===y&&r.seen[y][x]);panel='observe:'+(enemy?enemyBy(enemy.id).name+' — '+enemyBy(enemy.id).lore+((game.up('sight')||game.p.eye)?' HP '+enemy.hp+'/'+enemy.maxHp:''):loot?itemBy(loot.id).name+' — '+itemBy(loot.id).lore:b.getAttribute('aria-label'));inspect=false;render();return;}if(targetIndex!==null){if(game.use(targetIndex,'throw',{x,y})){targetIndex=null;after();}else toast('視界内・5マス以内の敵を選んでください。');return;}const dx=x-game.p.x,dy=y-game.p.y;if(Math.abs(dx)+Math.abs(dy)===0){game.interact();after();return;}if(Math.abs(dx)>Math.abs(dy))game.move(Math.sign(dx),0);else game.move(0,Math.sign(dy));after();}});
let touch=null,suppressClick=0;document.addEventListener('pointerdown',e=>{if(e.target.closest('.board'))touch={x:e.clientX,y:e.clientY};});document.addEventListener('pointerup',e=>{if(!touch)return;const dx=e.clientX-touch.x,dy=e.clientY-touch.y;touch=null;if(Math.max(Math.abs(dx),Math.abs(dy))<24||overlay.innerHTML||targetIndex!==null||inspect)return;suppressClick=Date.now()+350;if(Math.abs(dx)>Math.abs(dy))game.move(Math.sign(dx),0);else game.move(0,Math.sign(dy));after();});document.addEventListener('pointercancel',()=>touch=null);
document.addEventListener('keydown',e=>{if(e.key==='Tab'&&overlay.innerHTML){const bs=[...overlay.querySelectorAll('button:not(:disabled)')];if(bs.length){const i=bs.indexOf(document.activeElement);if(e.shiftKey&&(i<=0)){e.preventDefault();bs.at(-1).focus();}else if(!e.shiftKey&&(i===bs.length-1||i<0)){e.preventDefault();bs[0].focus();}}return;}if(e.key==='Escape'){if(panel){panel=null;renderPanel();}else{targetIndex=null;inspect=false;render();}return;}if(view!=='play'||overlay.innerHTML)return;const keys={ArrowUp:'move:0:-1',w:'move:0:-1',ArrowDown:'move:0:1',s:'move:0:1',ArrowLeft:'move:-1:0',a:'move:-1:0',ArrowRight:'move:1:0',d:'move:1:0',' ':'wait',e:'interact',q:'skill',i:'bag'};if(keys[e.key]){e.preventDefault();action(keys[e.key]);}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)save();});
render();
