import {CLASSES,ENEMIES,ITEMS,TALENTS,UPGRADES,CAUSES,itemBy,enemyBy} from './data.js';
export const W=11,H=13;
const dist=(a,b)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
export function fresh(){return {version:1,souls:0,upgrades:{},graves:[],codex:{enemies:[],items:[],causes:[],events:[]},deaths:{},unlocks:[],runs:0,run:null};}
export class Game{
 constructor(save=fresh(),rng=Math.random){this.s=save;this.rng=rng;this.notice='';}
 roll(n){return Math.floor(this.rng()*n);} pick(a){return a[this.roll(a.length)];} get r(){return this.s.run;} get p(){return this.r?.p;} up(id){return this.s.upgrades[id]||0;} has(id){return this.p?.talents.includes(id);} record(kind,id){if(!this.s.codex[kind].includes(id))this.s.codex[kind].push(id);}
 log(t){this.r.log.unshift(t);this.r.log=this.r.log.slice(0,40);}
 start(id){const c=CLASSES.find(c=>c.id===id);if(!c||c.unlock&&!this.s.unlocks.includes(c.unlock))return false;
 this.s.runs++;const names=['ノア','ウル','ニム','エダ','ロウ','ミル','オル','セナ'];this.s.run={id:this.s.runs,class:id,name:this.pick(names)+' '+this.s.runs+'世',floor:1,turn:0,kills:0,earned:0,log:[],choices:[],status:'alive',p:{x:1,y:1,hp:c.hp+this.up('vigor')*4,maxHp:c.hp+this.up('vigor')*4,atk:c.atk,level:1,xp:0,food:100,poison:0,fire:0,cool:0,talents:[],bag:[...c.items,...Array(this.up('pocket')).fill('potion')],weapon:c.items[0],armor:null,forge:0,eye:false,explored:0}};this.p.bag.forEach(id=>this.record('items',id));this.floor();this.log('灯りはひとつ。帰り道は、まだある。');return true;}
 floor(){const r=this.r;r.map=Array.from({length:H},()=>Array(W).fill('#'));
 const rooms=[[1,1],[6,1],[1,7],[6,7]].map(([x,y])=>({x:x+this.roll(2),y:y+this.roll(2),w:2+this.roll(3),h:2+this.roll(3)}));
 const carve=(x,y)=>{if(x>0&&x<W-1&&y>0&&y<H-1)r.map[y][x]='.';};
 for(const room of rooms)for(let y=room.y;y<Math.min(H-1,room.y+room.h);y++)for(let x=room.x;x<Math.min(W-1,room.x+room.w);x++)carve(x,y);
 let x=1,y=1;const order=[rooms[0],...rooms.slice(1).sort(()=>this.rng()-.5)];
 for(const room of order){const tx=Math.min(W-2,room.x+1),ty=Math.min(H-2,room.y+1);const horizontalFirst=this.roll(2);const walkX=()=>{while(x!==tx){carve(x,y);x+=Math.sign(tx-x);}carve(x,y);};const walkY=()=>{while(y!==ty){carve(x,y);y+=Math.sign(ty-y);}carve(x,y);};if(horizontalFirst){walkX();walkY();}else{walkY();walkX();}}
 r.map[1][1]='.';this.p.x=1;this.p.y=1;r.seen=Array.from({length:H},()=>Array(W).fill(false));r.visible=[];r.enemies=[];r.loot=[];r.fields=[];r.traps=[];r.sites=[];
 const cells=[];for(let y=1;y<H-1;y++)for(let x=1;x<W-1;x++)if(r.map[y][x]==='.'&&x+y>5)cells.push({x,y});cells.sort((a,b)=>(b.x+b.y)-(a.x+a.y));r.stairs=cells.shift()||{x:1,y:1};
 const take=()=>cells.splice(this.roll(cells.length),1)[0];
 const pool=ENEMIES.filter(e=>e.min<=r.floor&&e.id!=='boss'&&(e.id!=='wyrm'||this.up('dragon'))&&(e.id!=='tax'||this.up('god')));
 for(let i=0;i<5+Math.floor(r.floor/2)&&cells.length;i++){const pos=take(),e=this.pick(pool.filter(e=>e.min>=Math.max(1,r.floor-4)) .length?pool.filter(e=>e.min>=Math.max(1,r.floor-4)):pool);r.enemies.push({...pos,id:e.id,hp:e.hp+Math.floor(r.floor/3),maxHp:e.hp+Math.floor(r.floor/3),poison:0,fire:0,frozen:0});}
 if(r.floor===10)r.enemies.push({...r.stairs,id:'boss',hp:78,maxHp:78,poison:0,fire:0,frozen:0});
 if(this.up('dragon')&&r.floor>=3&&r.enemies.length){const e=r.enemies[0];Object.assign(e,{id:'wyrm',hp:22,maxHp:22});}
 if(this.up('god')&&r.floor>=4&&r.enemies.length>1){const e=r.enemies[1];Object.assign(e,{id:'tax',hp:19,maxHp:19});}
 const lootPool=ITEMS.filter(i=>i.id!=='brand'||this.up('dragon'));
 for(let i=0;i<5&&cells.length;i++)r.loot.push({...take(),id:i===0?'bread':i===1?'potion':this.pick(lootPool).id});
 if(this.up('garden')&&r.floor>3&&cells.length)r.loot.push({...take(),id:this.pick(['meat','root','heart','mushroom'])});
 for(let i=0;i<2+(this.up('garden')&&r.floor>3?3:0)&&cells.length;i++)r.traps.push({...take(),type:this.pick(['poison','fire']),used:false});
 if(this.up('smith')&&r.floor%2===0&&cells.length)r.sites.push({...take(),type:'smith',used:false});
 if(this.up('god')&&r.floor%2&&cells.length)r.sites.push({...take(),type:'altar',used:false});
 if(this.s.graves.length&&cells.length)r.sites.push({...take(),type:'grave',grave:this.pick(this.s.graves).id,used:false});
 this.reveal();}
 reveal(){const r=this.r;let count=0;r.visible=[];for(let y=0;y<H;y++)for(let x=0;x<W;x++){if(dist(this.p,{x,y})<=4&&this.line(this.p,{x,y})){r.visible.push(y*W+x);if(!r.seen[y][x]){r.seen[y][x]=true;if(r.map[y][x]==='.')count++;}}}this.p.explored+=count;if(this.p.explored>=8){if(this.has('scout'))this.heal(Math.floor(this.p.explored/8)*2);this.p.explored%=8;}r.enemies.filter(e=>this.visible(e)).forEach(e=>this.record('enemies',e.id));}
 line(a,b){let x=a.x,y=a.y,dx=Math.abs(b.x-x),dy=-Math.abs(b.y-y),sx=x<b.x?1:-1,sy=y<b.y?1:-1,err=dx+dy;while(x!==b.x||y!==b.y){const e=2*err;if(e>=dy){err+=dy;x+=sx;}if(e<=dx){err+=dx;y+=sy;}if(x===b.x&&y===b.y)return true;if(this.r.map[y]?.[x]==='#')return false;}return true;}
 visible(e){return this.r.visible.includes(e.y*W+e.x);} heal(n){this.p.hp=Math.min(this.p.maxHp,this.p.hp+n);} ready(){return this.r?.status==='alive'&&!this.r.choices.length;}
 move(dx,dy){if(!this.ready()||Math.abs(dx)+Math.abs(dy)!==1)return false;const x=this.p.x+dx,y=this.p.y+dy;if(this.r.map[y]?.[x]!=='.')return false;const e=this.r.enemies.find(e=>e.x===x&&e.y===y);if(e){const w=itemBy(this.p.weapon);this.hit(e,this.p.atk+(w?.power||0)+this.p.forge+(this.has('blood')&&this.p.hp<this.p.maxHp/2?4:0)+(this.has('hunger')&&this.p.food===0?3:0));if(this.r.enemies.includes(e)){if(this.has('venom')||w?.tag==='poison')e.poison=4+(this.has('rot')?3:0);if(this.has('ember')||w?.tag==='fire')e.fire=3;}if(this.has('leech'))this.heal(1);}else{this.p.x=x;this.p.y=y;this.reveal();const t=this.r.traps.find(t=>t.x===x&&t.y===y&&!t.used);if(t){t.used=true;this.p[t.type]=4;this.record('events',t.type+'trap');this.log(t.type==='poison'?'床がくしゃみをした。毒だ。':'床の灯りが、靴に燃え移った。');}this.pickup();}this.tick();return true;}
 pickup(){for(const i of [...this.r.loot])if(dist(i,this.p)===0){if(this.p.bag.length>=9+this.up('pocket')*3){this.log('鞄がいっぱいだ。荷物を使うか置こう。');break;}this.p.bag.push(i.id);this.record('items',i.id);this.r.loot.splice(this.r.loot.indexOf(i),1);this.log(itemBy(i.id).name+'を拾った。');}}
 hit(e,n){if(!this.r.enemies.includes(e))return;const d=Math.max(1,n-(enemyBy(e.id).trait==='armor'?2:0));e.hp-=d;this.log(enemyBy(e.id).name+'に'+d+'。');if(e.hp<=0)this.kill(e);}
 kill(e){const r=this.r;r.enemies.splice(r.enemies.indexOf(e),1);r.kills++;this.p.xp+=4+enemyBy(e.id).min;r.earned++;this.record('enemies',e.id);this.log(enemyBy(e.id).name+'は静かになった。');if(this.has('feast')){this.heal(2);this.p.food=Math.min(100,this.p.food+7);}if(r.class==='forager'&&this.roll(3)===0)r.loot.push({x:e.x,y:e.y,id:'meat'});if(this.has('plague')&&e.poison)r.enemies.filter(o=>dist(o,e)<=3).forEach(o=>o.poison=5);if(this.has('blast'))for(const o of [...r.enemies])if(dist(o,e)<=2)this.hit(o,this.has('fuse')?10:6);if(e.id==='boss'){this.record('events','king');this.log('根の王が倒れた。階段の先で、この生を世界へ返せる。');}this.checkLevel();}
 checkLevel(){const p=this.p;if(p.xp>=p.level*10&&!this.r.choices.length){p.xp-=p.level*10;p.level++;p.maxHp+=3;this.heal(8);const pool=TALENTS.filter(t=>!p.talents.includes(t.id)&&(!t.unlock||this.s.unlocks.includes(t.unlock)));this.r.choices=[];while(pool.length&&this.r.choices.length<3)this.r.choices.push(pool.splice(this.roll(pool.length),1)[0].id);this.log('Lv.'+p.level+'。何かが身体に残った。');}}
 choose(id){if(!this.r.choices.includes(id))return;this.p.talents.push(id);this.r.choices=[];this.checkLevel();}
 hurt(n,cause,detail){if(this.r.status!=='alive')return;this.p.hp-=cause==='divine'&&this.has('grace')?Math.ceil(n/2):n;if(this.p.hp<=0)this.die(cause,detail);}
 tick(){const r=this.r,p=this.p;if(r.status!=='alive')return;r.turn++;p.cool=Math.max(0,p.cool-1);if(r.turn%3===0)p.food=Math.max(0,p.food-1);if(p.food===0&&!this.has('hunger'))this.hurt(1,'hunger','食事の予定を先延ばしにした');
 for(const type of ['poison','fire'])if(p[type]>0){p[type]--;const immune=type==='poison'?(r.class==='mold'||this.has('rot')):(this.has('phoenix')||itemBy(p.armor)?.tag==='fireproof');if(!immune)this.hurt(2,type,type==='poison'?'毒が最後の頁まで回った':'灯りと自分の区別がつかなくなった');else if(type==='fire'&&this.has('phoenix'))this.heal(1);}
 for(const e of [...r.enemies]){if(r.status!=='alive')break;if(!r.enemies.includes(e))continue;for(const type of ['poison','fire'])if(e[type]>0){e[type]--;this.hit(e,2);}if(!r.enemies.includes(e))continue;if(e.frozen>0){e.frozen--;continue;}if(dist(e,p)<=1){const b=enemyBy(e.id),armor=(itemBy(p.armor)?.power||0)+(this.has('guard')?1:0);const damage=Math.max(1,b.atk+Math.floor(r.floor/4)-armor);this.log(b.name+'の攻撃。−'+damage+' HP');this.hurt(damage,b.trait==='divine'?'divine':'combat',b.name+'に倒された');if(['poison','fire','dragon'].includes(b.trait))p[b.trait==='poison'?'poison':'fire']=3;if(b.trait==='hunger')p.food=Math.max(0,p.food-8);if(b.trait==='drain')e.hp=Math.min(e.maxHp,e.hp+2);}else if(dist(e,p)<=6&&this.line(e,p)){const opts=[{x:e.x+Math.sign(p.x-e.x),y:e.y},{x:e.x,y:e.y+Math.sign(p.y-e.y)}].filter(o=>dist(o,e)===1&&r.map[o.y]?.[o.x]==='.'&&!r.enemies.some(z=>z!==e&&dist(z,o)===0)&&dist(p,o)>0);if(opts.length)Object.assign(e,this.pick(opts));if(enemyBy(e.id).trait==='fast'&&r.turn%2===0&&dist(e,p)>1){const dx=Math.sign(p.x-e.x),dy=Math.sign(p.y-e.y);const next=[{x:e.x+dx,y:e.y},{x:e.x,y:e.y+dy}].find(o=>dist(o,e)===1&&r.map[o.y]?.[o.x]==='.'&&!r.enemies.some(z=>z!==e&&dist(z,o)===0)&&dist(p,o)>0);if(next)Object.assign(e,next);}}}
 if(r.status==='alive'){this.pickup();this.reveal();}}
 wait(){if(!this.ready())return;this.log('耳を澄ませた。');this.tick();}
 skill(){if(!this.ready()||this.p.cool)return false;const c=CLASSES.find(c=>c.id===this.r.class),es=this.r.enemies.filter(e=>this.visible(e)).sort((a,b)=>dist(a,this.p)-dist(b,this.p));let used=false;const bonus=this.has('blood')&&this.p.hp<this.p.maxHp/2?4:0;if(c.id==='warden'){for(const e of [...es])if(dist(e,this.p)===1){this.hit(e,this.p.atk+(itemBy(this.p.weapon)?.power||0)+this.p.forge+4+bonus);used=true;}}if(c.id==='scribe'&&es.length){this.hit(es[0],8+bonus);used=true;}if(c.id==='forager'&&this.p.food>=15){this.p.food-=15;this.heal(12);used=true;}if(c.id==='mold'&&es.length){es.forEach(e=>e.poison=6);used=true;}if(used){this.p.cool=Math.max(2,c.cool-(this.has('stride')?2:0))+1;this.log(c.skill+'。');this.tick();}else this.log('今は技を使う相手か、食料がない。');return used;}
 use(index,action,target){if(!this.ready())return false;const id=this.p.bag[index],i=itemBy(id);if(!i)return false;const p=this.p,r=this.r;
 if(action==='equip'){if(!['weapon','armor'].includes(i.type))return false;p[i.type]=id;this.log(i.name+'を装備した。');this.tick();return true;}
 if(action==='drop'){p.bag.splice(index,1);if(p.weapon===id&&!p.bag.includes(id))p.weapon=null;if(p.armor===id&&!p.bag.includes(id))p.armor=null;r.loot.push({x:p.x,y:p.y,id});this.log(i.name+'を置いた。');this.tickWithoutPickup();return true;}
 if(action==='throw'){if(!target||!this.visible(target)||dist(target,p)>5)return false;const e=r.enemies.find(e=>dist(e,target)===0);if(!e)return false;if(i.type==='bomb'){for(const o of [...r.enemies])if(dist(o,target)<=2)this.hit(o,i.power+(this.has('throw')?6:0));if(dist(p,target)<=2)this.hurt(this.has('fuse')?7:14,'explosion','投げた壺より腕が短かった');}else{this.hit(e,i.power+(this.has('throw')?6:0));if(r.enemies.includes(e)){if(i.type==='poison')e.poison=6;if(i.type==='fire')e.fire=4;if(i.type==='frost')e.frozen=3;if(i.type==='salt'&&e.id==='skeleton')this.hit(e,8);}}}
 else if(action==='break'){if(i.type==='bomb'){for(const e of [...r.enemies])if(dist(e,p)<=2)this.hit(e,14);this.hurt(this.has('fuse')?7:14,'explosion','せっかちな壺の気持ちを理解した');}else if(i.type==='mirror'){p.atk+=2;this.hurt(7,'mirror','鏡の批評に耐えられなかった');}else if(i.type==='fire')p.fire=5;else if(i.type==='poison')p.poison=5;else{r.earned++;this.log('破片に、小さな残響を見つけた。');}}
 else if(action==='use'){switch(i.type){case 'food':p.food=Math.min(100,p.food+i.power);this.heal(3);if(i.tag==='toxic')p.poison=6;if(i.tag==='hot')p.fire=4;if(i.tag==='meat')p.atk++;if(i.tag==='cure')p.poison=0;if(this.has('gourmet')){p.maxHp+=2;this.heal(2);}break;case 'potion':this.heal(i.power);break;case 'cure':p.poison=p.fire=0;break;case 'poison':p.poison=6;break;case 'fire':p.fire=6;break;case 'map':r.seen=r.seen.map(row=>row.map(()=>true));break;case 'heart':p.maxHp+=i.power;this.heal(i.power);break;case 'relic':r.earned+=i.power;break;case 'eye':p.eye=true;break;case 'seed':this.heal(5);for(let y=0;y<H;y++)for(let x=0;x<W;x++)if(dist(p,{x,y})<7)r.seen[y][x]=true;break;case 'scroll':if(r.floor<10){r.floor++;this.floor();}else this.heal(15);break;default:return false;}}
 else return false;
 p.bag.splice(index,1);if(p.weapon===id&&!p.bag.includes(id))p.weapon=null;if(p.armor===id&&!p.bag.includes(id))p.armor=null;this.log(i.name+'を'+(action==='throw'?'投げた':action==='break'?'壊した':'使った')+'。');this.tick();return true;}
 tickWithoutPickup(){const loot=this.r.loot;this.r.loot=[];this.tick();this.r.loot.push(...loot);}
 interact(){if(!this.ready())return;const r=this.r,p=this.p;const site=r.sites.find(s=>dist(s,p)===0&&!s.used);if(site){site.used=true;this.record('events',site.type);if(site.type==='smith'){p.forge+=2;this.hurt(5,'combat','鍛冶屋への支払いに血が足りなかった');this.log('「勘定は血で」。武器の鍛造 +2。');}if(site.type==='altar'){p.atk+=2;r.earned+=3;this.hurt(6,'divine','神はお釣りを持っていなかった');this.log('神が応えた。攻撃+2、残響+3、HP−6。');}if(site.type==='grave'){const g=this.s.graves.find(g=>g.id===site.grave);this.log('「'+g.name+'／'+g.detail+'」 残響を2拾った。');r.earned+=2;this.heal(4);}this.tick();return;}
 if(dist(p,r.stairs)===0){if(r.floor===10){if(r.enemies.some(e=>e.id==='boss')){this.log('王がまだ出口を塞いでいる。');return;}this.die('victory','根の王を討ち、生を世界へ還した');}else{r.floor++;p.food=Math.min(100,p.food+12);this.heal(3);this.floor();this.log('第'+r.floor+'層。空気が少し違う。');}}else this.log('階段・墓・施設の上で「調べる」。');}
 die(cause,detail){if(this.r.status!=='alive')return;const r=this.r,p=this.p;r.status=cause==='victory'?'victory':'dead';p.hp=Math.max(0,p.hp);const reward=Math.ceil((4+r.floor*2+Math.floor(r.kills/2)+r.earned+(cause==='victory'?25:0))*(this.up('dragon')?1.3:1));this.s.souls+=reward;this.s.deaths[cause]=(this.s.deaths[cause]||0)+1;this.record('causes',cause);r.newUnlocks=[];if(['poison','fire','hunger','explosion','divine'].includes(cause)&&!this.s.unlocks.includes(cause)){if(cause!=='poison'||this.s.deaths[cause]>=2){this.s.unlocks.push(cause);r.newUnlocks.push(cause);}}const grave={id:r.id,name:r.name,class:r.class,floor:r.floor,level:p.level,cause,detail,equipment:[p.weapon,p.armor].filter(Boolean),talents:[...p.talents],turn:r.turn,date:new Date().toISOString(),reward,echo:{kind:'grave',met:0}};this.s.graves.unshift(grave);r.result=grave;}
 buy(id){const u=UPGRADES.find(u=>u.id===id);if(!u||this.r?.status==='alive'||this.up(id)>=u.max)return false;const cost=u.cost*(this.up(id)+1);if(this.s.souls<cost)return false;this.s.souls-=cost;this.s.upgrades[id]=this.up(id)+1;return true;}
}
export function loadSave(storage){try{const s=JSON.parse(storage.getItem('remains-v1'));if(!s||s.version!==1||!s.codex||!Array.isArray(s.graves)||typeof s.souls!=='number'||!s.upgrades||!Array.isArray(s.unlocks)||!s.deaths||!['enemies','items','causes','events'].every(k=>Array.isArray(s.codex[k])))return fresh();if(s.run&&(!s.run.p||!Array.isArray(s.run.map)||!Array.isArray(s.run.enemies)||!Array.isArray(s.run.p.bag)))return fresh();return s;}catch{return fresh();}}
